### ISSUE TITLE
Warning: [react-router] props.history and context.history are deprecated. Please use context.router

### ISSUE THREAD

**Issue by Fedcomp** [react-ui-by-dtrussia-wip/core#24]
http://tiny.cc/router-contextchanges

```
Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`
```

In the browser console with react-ui.

It seems that in react router 2.x mixins like props.history and others are not used anymore, since react documented `context` usage. So, now only context.router is available.

**Comment by imevro** [comment]
We will support react-router 2 after it's release.
